#version 450
#extension GL_GOOGLE_include_directive : require
#include "commonrt.glsl"
struct pushConsts {
    uint64_t vertsBufferAddress;
    uint64_t idxBufferAddress;
    uint64_t outBufferAddress;
    uint64_t oriBufferAddress;
    uint64_t dirBufferAddress;
    uint64_t hitBufferAddress;
    uint64_t energyBufferAddress;
    uint64_t currentTri;
};

struct hitInfo {
    uint64_t tri;
    float energy;
};


void main() {

}